---
title: "Faster than thought: Detecting sub-second activation sequences with sequential fMRI pattern analysis"
subtitle: "Short project title: highspeed"
author:
  - Lennart Wittkuhn^[Max Planck Institute for Human Development, wittkuhn@mpib-berlin.mpg.de]
  - Nicolas W. Schuck^[Max Planck Institute for Human Development, schuck@mpib-berlin.mpg.de]
date: "Last update: `r format(Sys.time(), '%d %B, %Y')`"
output:
 html_document:
    toc: true
    self_contained: true
    toc_float: true
    toc_depth: 3
    number_sections: true
    highlight: pygments
    theme: cosmo
    df_print: paged
    fig_caption: true
fig.align: "center"
header-includes:
  - \usepackage{fontspec}
  - \setmainfont{AgfaRotisSansSerif}
email: wittkuhn@mpib-berlin.mpg.de
---

```{r, echo=FALSE, message=FALSE, include=FALSE}
if (!requireNamespace("pacman")) install.packages("pacman")
packages_cran <- c("here")
pacman::p_load(char = packages_cran)
if (basename(here::here()) == "highspeed"){
  path_root = here::here("highspeed-mriqc")
} else {
  path_root = here::here()
}
```

# MRI quality control

## Step 1: MRI quality control using [MRIQC](https://mriqc.readthedocs.io/en/stable/)

### Overview

> MRIQC extracts no-reference IQMs (image quality metrics) from structural (T1w and T2w) and functional MRI (magnetic resonance imaging) data.

Please see the [official MRIQC documentation](https://mriqc.readthedocs.io/en/stable/) for details and refer to the paper listed in the References section.

### Code and software

#### `mriqc` container, version 0.15.2rc1

MRIQC quality control was performed using [`mriqc`](https://mriqc.readthedocs.io/en/stable/), version 0.15.2rc1

``` bash
singularity pull docker://poldracklab/mriqc:0.15.2rc1
```

#### MRIQC subject-level reports: `highspeed-mriqc-subject-level.sh`

First, MRIQC has to run on the individual subject-, (if available, session-), modality- and run- level.
This is achieved by running the `highspeed-mriqc-subject-level.sh` shell-script.
The script is parallelizing all subjects, sessions, modalities and runs on the cluster.

```{bash, echo=TRUE, code=readLines(file.path(path_root, "code", "mriqc", "highspeed-mriqc-subject-level.sh")), eval=FALSE}
```

#### MRIQC group-level reports: `highspeed-mriqc-group-level.sh`

Afterwards, one can run the `highspeed-mriqc-group-level.sh` script to acquire group statistics of the quality metrics.

```{bash, echo=TRUE, code=readLines(file.path(path_root, "code", "mriqc", "highspeed-mriqc-group-level.sh")), eval=FALSE}
```

### References

> Esteban, O., Birman, D., Schaer, M., Koyejo, O. O., Poldrack, R. A., & Gorgolewski, K. J. (2017). MRIQC: Advancing the automatic prediction of image quality in MRI from unseen sites. PLoS ONE, 12(9), e0184661. [doi: 10.1371/journal.pone.0184661](https://doi.org/10.1371/journal.pone.0184661)
